show_downloads: true
theme: jekyll-theme-minimal
github:
  is_project_page: true
description:  <a href="https://lalutir.github.io" target="_blank">Main portfolio page</a>
gh_sponsor: lalutir
markdown: GFM
