from setuptools import setup, find_packages

setup(
    name='f1-analysis',
    version='1.0.0',
    description='A toolkit for analyzing Formula 1 data using FastF1 library',
    long_description='''\
        f1-analysis is a toolkit for analyzing Formula 1 data, leveraging the FastF1 library in Python. It provides functionalities for retrieving, manipulating, and analyzing telemetry and race data, facilitating in-depth insights into various aspects of Formula 1 races.''',
    author='lalutir',
    author_email='f1.analysis.contact@gmail.com',
    url='https://github.com/lalutir/f1-analysis',
    packages=find_packages(),
    install_requires=[
        'fastf1',
        'matplotlib==3.5.1',
        'numpy==1.21.5',
        'pandas==1.4.1',
        'requests==2.28.1',
        'requests-cache==1.0.0',
        'scipy==1.7.3',
        'timple==0.1.6',
        'websockets==10.3',
        'autodocsumm>=0.2.10',
        'furo',
        'isort',
        'kaleido',
        'plotly',
        'pre-commit',
        'pytest>=6.0.0',
        'pytest-mpl==0.14.0',
        'requests-mock',
        'ruff',
        'seaborn>0.13.0',
        'sphinx>6.0',
        'sphinx-autodoc-typehints',
        'sphinx-gallery>=0.10.0',
        'wheel',
        'xdoctest'
    ],
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ],
)
